include:
  - ./compose/coturn/compose.yaml
  - ./compose/kafka/compose.yaml
  - ./compose/livekit/compose.yaml
  - ./compose/minio/compose.yaml
  - ./compose/postgres/compose.yaml

networks:
  verse-network:
    driver: bridge
    name: verse-network
